test_that("read_gcp() works and handles errors", {

  gcp_data <- create_dummy_gcp_data(10)

  # Train the model using the GCPs generated by create_demo_data()
  gcps <- read_gcp(
    source_x = gcp_data$source_x,
    source_y = gcp_data$source_y,
    target_x = gcp_data$source_x + gcp_data$dx,
    target_y = gcp_data$source_y + gcp_data$dy
  )

  expect_s3_class(gcps, "gcp")
  expect_s3_class(gcps, "data.frame")
  expect_named(gcps, c("source_x", "source_y", "target_x", "target_y", "dx", "dy"))

})

test_that("read_gcp() returns errors", {
  gcp_data <- create_dummy_gcp_data(10)

  # Non-numeric input
  expect_error(
    read_gcp(
      source_x = as.character(gcp_data$source_x),
      source_y = gcp_data$source_y,
      target_x = gcp_data$source_x + gcp_data$dx,
      target_y = gcp_data$source_y + gcp_data$dy
    ),
    "All input coordinates must be finite numbers."
  )

  # Mismatched lengths
  expect_error(
    read_gcp(
      source_x = gcp_data$source_x,
      source_y = gcp_data$source_y[-1], # Shorter length
      target_x = gcp_data$source_x + gcp_data$dx,
      target_y = gcp_data$source_y + gcp_data$dy
    ),
    "All input vectors must have the same length."
  )

  # NA values
  gcp_data_with_na <- gcp_data
  gcp_data_with_na$source_x[1] <- NA
  expect_error(
    read_gcp(
      source_x = gcp_data_with_na$source_x,
      source_y = gcp_data_with_na$source_y,
      target_x = gcp_data_with_na$source_x + gcp_data_with_na$dx,
      target_y = gcp_data_with_na$source_y + gcp_data_with_na$dy
    ),
    "All input coordinates must be finite numbers."
  )
})

test_that("print.gcp displays correct output", {
  gcp_data <- create_dummy_gcp_data(10)
  gcps <- read_gcp(
    source_x = gcp_data$source_x,
    source_y = gcp_data$source_y,
    target_x = gcp_data$source_x + gcp_data$dx,
    target_y = gcp_data$source_y + gcp_data$dy
  )

  expect_output(print(gcps), "GCP Object with 10 points")

  gcp_data <- create_dummy_gcp_data(12)
  gcps <- read_gcp(
    source_x = gcp_data$source_x,
    source_y = gcp_data$source_y,
    target_x = gcp_data$source_x + gcp_data$dx,
    target_y = gcp_data$source_y + gcp_data$dy
  )

  expect_output(print(gcps), "GCP Object with 12 points")

})

test_that("summary.gcp displays correct summary", {
  gcp_data <- create_dummy_gcp_data(10)
  gcps <- read_gcp(
    source_x = gcp_data$source_x,
    source_y = gcp_data$source_y,
    target_x = gcp_data$source_x + gcp_data$dx,
    target_y = gcp_data$source_y + gcp_data$dy
  )

  expect_output(summary(gcps), "Summary of GCP Object:")
  expect_output(summary(gcps), "Number of points: 10")
  expect_output(summary(gcps), "Source Coordinates Range:")
  expect_output(summary(gcps), "Target Coordinates Range:")
})

test_that("plot.gcp returns a valid ggplot object with correct data", {

  gcp_data <- create_dummy_gcp_data(10)
  gcps <- read_gcp(
    source_x = gcp_data$source_x,
    source_y = gcp_data$source_y,
    target_x = gcp_data$source_x + gcp_data$dx,
    target_y = gcp_data$source_y + gcp_data$dy
  )
  p <- plot(gcps)

  # Test 1: The output must be a ggplot object
  expect_s3_class(p, "ggplot")

  # Test 2: Check if exaggeration factor works
  exaggeration_factor <- 2
  p_exaggerated <- plot(
    gcps,
    exaggeration_factor = exaggeration_factor
  )
  plot_data <- ggplot2::layer_data(p_exaggerated, 1)

  # Calculate expected endpoints
  expected_xend <- gcps$source_x +
    exaggeration_factor * (gcps$target_x - gcps$source_x)
  expected_yend <- gcps$source_y +
    exaggeration_factor * (gcps$target_y - gcps$source_y)

  # Check if the calculated endpoints in the plot match the expected ones
  expect_equal(plot_data$xend, expected_xend)
  expect_equal(plot_data$yend, expected_yend)

})
