# Unit tests for the helmert model in the mapAI package

test_that("helmert model returns a valid object", {

  gcp_data <- create_dummy_gcp_data()

  # Train the model using the GCPs generated by create_demo_data()
  helmert_model <- helmert(
    source_x = gcp_data$source_x,
    source_y = gcp_data$source_y,
    target_x = gcp_data$source_x + gcp_data$dx,
    target_y = gcp_data$source_y + gcp_data$dy
  )


  # Check the class and structure
  expect_s3_class(helmert_model, "helmert")
  expect_named(helmert_model$coefficients, c("a", "b"))
  expect_named(helmert_model$centroids, c("u_mean", "v_mean", "x_mean", "y_mean"))
})

test_that("predict.helmert works with valid input", {
  gcp_data <- create_dummy_gcp_data()

  helmert_model <- helmert(
    source_x = gcp_data$source_x,
    source_y = gcp_data$source_y,
    target_x = gcp_data$source_x + gcp_data$dx,
    target_y = gcp_data$source_y + gcp_data$dy
  )

  new_points <- data.frame(
    source_x = c(25, 5),
    source_y = c(18, 8)
  )

  predicted_points <- predict(helmert_model, new_points)

  expect_true(is.data.frame(predicted_points))
  expect_named(predicted_points, c("target_x", "target_y"))
  expect_equal(nrow(predicted_points), nrow(new_points))
  expect_true(all(is.finite(predicted_points$target_x)))
  expect_true(all(is.finite(predicted_points$target_y)))
})

test_that("print.helmert displays model summary", {
  gcp_data <- create_dummy_gcp_data()

  helmert_model <- helmert(
    source_x = gcp_data$source_x,
    source_y = gcp_data$source_y,
    target_x = gcp_data$source_x + gcp_data$dx,
    target_y = gcp_data$source_y + gcp_data$dy
  )

  expect_output(print(helmert_model), "Helmert Transformation Model")
  expect_output(print(helmert_model$coefficients), "a          b")
  expect_output(print(helmert_model$centroids), "u_mean   v_mean   x_mean   y_mean")
})

test_that("predict.helmert handles invalid input gracefully", {
  gcp_data <- create_dummy_gcp_data()

  helmert_model <- helmert(
    source_x = gcp_data$source_x,
    source_y = gcp_data$source_y,
    target_x = gcp_data$source_x + gcp_data$dx,
    target_y = gcp_data$source_y + gcp_data$dy
  )

  lm_model <- lm(dx ~ source_x + source_y, data = gcp_data)
  expect_error(mapAI:::predict.helmert(lm_model, data.frame(source_x = c(1), source_y = c(2))),
                      "The 'object' provided must be of class 'helmert'.")

  # Missing required columns
  expect_error(
    predict(helmert_model, data.frame(x = c(1), y = c(2))),
    "'newdata' must be a data frame with columns 'source_x' and 'source_y'."
  )

  # Non-finite values
  expect_error(
    predict(helmert_model, data.frame(source_x = c(1, NA), source_y = c(2, 3))),
    "All 'source_x' and 'source_y' values in 'newdata' must be finite numbers."
  )
})

